# include in server {} block

ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;

# OCSP Stapling
ssl_stapling on;
ssl_stapling_verify on;

lua_ssl_trusted_certificate /usr/local/share/certs/ca-root-nss.crt;   # freebsd
#lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;   # ubuntu
lua_ssl_verify_depth 2;

# Generate Diffie-Hellman keys:  openssl dhparam -out dhparam.pem 2048
ssl_dhparam certs/dhparam.pem;

# Optimize session cache
ssl_session_cache shared:SSL:40m;
ssl_session_timeout 4h;
ssl_session_tickets off;

# security headers
add_header X-Frame-Options DENY;
add_header X-XSS-Protection "1; mode=block" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "no-referrer-when-downgrade" always;
add_header Content-Security-Policy "default-src * data: blob: 'unsafe-eval' 'unsafe-inline'" always;
#add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

